---
title: "R Notebook"
output: html_notebook
---

正規・非正規の動向を評価するためのdataを整備する。

```{r}
library(tidyverse)
library(readxl)
library(here)
library(magrittr)


files <-  list.files(here("data","sangyo"),
                     pattern = "xls",
                     full.names = TRUE)

vertical_name <- c('総数','今月いた15歳以上人口','労働力人口','就業者','農業林業','非農林業','漁業','鉱業採石業砂利採取業','建設業','製造業','電気ガス熱供給水道業','情報通信業','運輸業郵便業','卸売業小売業','金融業保険業','不動産業物品賃貸業','学術研究専門技術サービス業','宿泊業飲食サービス業','生活関連サービス業娯楽業','教育学習支援業','医療福祉','複合サービス事業','サービス業','公務','分類不能の産業','完全失業者','非労働力人口','就業状態不詳','前月いて今月いなかった者')

horizontal_name <- c('総数','前月いた15歳以上人口','労働力人口','就業者','農業林業','非農林業','漁業','鉱業採石業砂利採取業','建設業','製造業','電気ガス熱供給水道業','情報通信業','運輸業郵便業','卸売業小売業','金融業保険業','不動産業物品賃貸業','学術研究専門技術サービス業','宿泊業飲食サービス業','生活関連サービス業娯楽業','教育学習支援業','医療福祉','複合サービス事業','サービス業','公務','分類不能の産業','完全失業者','非労働力人口','就業状態
不詳','前月14歳で今月15歳の者','前月いなかった者')
```


```{r, warning=FALSE}
#就業形態は、"今月"_"先月"の順番で統一。

transition_cols <- c("sex",
                     "age",
                     "yyyymm",

                     "seiki_thismonth", #今月いた15歳以上人口から考える
                     "seiki_lastmonth", #先月いた15歳以上人口から考える
                     
                     "seiki_seiki",
                     "seiki_hiseiki",
                     "seiki_unemp",
                     "seiki_nilf",

                     
                     "hiseiki_seiki",
                     "unemp_seiki",
                     "nilf_seiki"



                     )



age_list <- c("total","15-34","35-54","55-")
sex_list <- c("total","male","female")

```

```{r}
    tmp <- read_xls(files[3],
         sheet = 1,
         range = "O12:AR41") %>% 
      mutate_all(as.numeric) %>% 
      mutate_all(~replace_na(.,0)) %>% 
      set_colnames(horizontal_name) %>% 
      mutate(thismonth_status = vertical_name)
```

##out of sample を除いたもの

```{r, warning=FALSE}
df_master <- NULL

for(i in files){
  
  for(j in 1:12){

  
  
    tmp <- read_xls(i,
         sheet = j,
         range = "O12:AR41") %>% 
      mutate_all(as.numeric) %>% 
      mutate_all(~replace_na(.,0)) %>% 
      set_colnames(horizontal_name) %>% 
      mutate(thismonth_status = vertical_name) %>% 
      mutate(yyyymm = i %>% str_sub(start = -10,end = -5) %>% as.numeric()) %>% 
      mutate(age = age_list[j - 4 *(ceiling(j/4)-1)] ) %>% 
      mutate(sex = sex_list[ceiling(j/4)]) %>% 
      select(yyyymm,age,sex,thismonth_status,everything())
      
    
    # df <- data.frame(matrix(ncol = length(transition_cols))[0,])
    # colnames(df) <- transition_cols
    # 
    # df[1,"age"] <- age_list[j - 4 *(ceiling(j/4)-1)] 
    # df[1,"sex"] <- sex_list[ceiling(j/4)]
    # 
    # df[1,"yyyymm"] <- i %>% str_sub(start = -10,end = -5) %>% as.numeric()
    # 
    # df[1,"seiki_lastmonth"] <- as.numeric(tmp[12,2])+as.numeric(tmp[26,2]) -as.numeric(tmp[12,42])-as.numeric(tmp[12,43])-as.numeric(tmp[26,42])-as.numeric(tmp[26,43])
    # 
    # df[1,"seiki_seiki"] <- as.numeric(tmp[12,12])+as.numeric(tmp[26,12]) +as.numeric(tmp[12,26])+as.numeric(tmp[26,26]) 
    # df[1,"seiki_hiseiki"] <- as.numeric(tmp[12,13])+as.numeric(tmp[26,13]) +as.numeric(tmp[12,27])+as.numeric(tmp[26,27])
    # df[1,"seiki_unemp"] <- as.numeric(tmp[12,36])+as.numeric(tmp[26,36])
    # df[1,"seiki_nilf"] <- as.numeric(tmp[12,37])+as.numeric(tmp[26,37])
    # 
    # df[1,"hiseiki_seiki"] <- as.numeric(tmp[13,12])+as.numeric(tmp[13,26]) +as.numeric(tmp[27,12])+as.numeric(tmp[27,26])
    # df[1,"unemp_seiki"] <- as.numeric(tmp[36,12])+as.numeric(tmp[36,26])
    # df[1,"nilf_seiki"] <- as.numeric(tmp[37,12])+as.numeric(tmp[37,26])
    # 
    # df[1,"seiki_thismonth"] <- as.numeric(tmp[2,12])+as.numeric(tmp[2,26])-as.numeric(tmp[42,12])+as.numeric(tmp[42,26])
    
    
    df_master <- rbind(df_master,tmp)
    
  }
}
    


write.csv(df_master,here("treated_data",str_c("industry_201301_",i %>% str_sub(start = -10,end = -5) %>% as.character(),".csv")),
          fileEncoding = "cp932")

```

